### ISSUE TITLE
example uses non-existent 'microsoft' module; should be 'msgraph'

### ISSUE THREAD

**Issue by eduvik** [microsoftarchive/msgraph-sdk-python#13]

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention.

**Comment by JGuzak** [comment]
Second this problem. Any information on when this will get fixed?

**Comment by caitlinrussell** [comment]
There were many issues with the existing sample, so I have deprecated it. I realize this doesn't solve the real issue, so I have created a new one to track creating a new, functional sample for this library: #20

**Comment by JGuzak** [comment]
Thank you for the update.
