### ISSUE TITLE
AuthProvider not implemented

### ISSUE THREAD

**Issue by elexpander** [microsoftarchive/msgraph-sdk-python#16]
SDK states "You must implement an authentication provider that derives from AuthProviderBase".

For ease of use, it would be very nice if the SDK provided authentication providers for the most common  scenarios: client app, daemon app...

**Comment by MIchaelMainer** [comment]
Hello @elexpander,

I agree that it would be much easier to use if the client library contained the authentication providers for the different scenarios. With that said, we aren't in a position to take on the authentication story for the Python Graph client library. We have to depend on other teams at Microsoft, or engineers outside of Microsoft, to define the authentication provider.

You can use https://github.com/AzureAD/azure-activedirectory-library-for-python in your AuthProvider.

We will take your feedback into consideration as you aren't the first to bring this up. Thank you for providing this feedback.
