### ISSUE TITLE
Broken link in main README

### ISSUE THREAD

**Issue by RobertoPrevato** [microsoftarchive/msgraph-sdk-python#17]
Hi,
Link _[https://graph.microsoft.io/en-us/docs/authorization/permission_scopes](https://graph.microsoft.io/en-us/docs/authorization/permission_scopes)_ in the main README is broken.

**Comment by dpim** [comment]
Hi Roberto, thanks for bringing this to our attention. The correct link for information about Graph permissions and scopes is: https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference

**Comment by caitlinrussell** [comment]
Thanks for finding this!

**Comment by RobertoPrevato** [comment]
My pleasure! Thanks for the great job.
