### ISSUE TITLE
Authentication code examples

### ISSUE THREAD

**Issue by General-Gouda** [microsoftarchive/msgraph-sdk-python#22]
Within the ReadMe Authentication section (https://github.com/microsoftgraph/msgraph-sdk-python#authentication) there are no examples on how to utilize the AuthProviderBase class. Then, in the Examples section below it simply states "instantiate your auth provider implementation here" which is not particularly helpful to novices such as myself.

Is there any way to include examples of what building the AuthProviderBase object looks like? Or can someone point me towards a How To for using this feature? 

Thank you!

**Comment by caitlinrussell** [comment]
We are in the process of writing some new samples that describe ways to complete authentication scenarios using different auth libraries. Is there a particular auth scenario that you would like to see included.

**Comment by General-Gouda** [comment]
@cbales Thanks for the reply! 

I am primarily looking for a way to authenticate a console app without the need for user intervention or login for my own purposes but I may be writing apps for our helpdesk to perform administrative functions in the future which would require login. But that also would be a console app or a winforms type app (Qt).

**Comment by zioalex** [comment]
+1 . I also trying to authenticate use msgraph but without success. Please can you share a draft example to try.

**Comment by caitlinrussell** [comment]
Closing as we are archiving this project
