### ISSUE TITLE
driver_builder.item_by_path not implemented. 

### ISSUE THREAD

**Issue by jonable** [microsoftarchive/msgraph-sdk-python#23]
Tried running the following command
`client.item(drive="me", path="/DemoFolder").children.request(top=3).get()`
With the following exception thrown.
`AttributeError: 'DriveRequestBuilder' object has no attribute 'item_by_path'`

Couldn't find method "item_by_path" defined in the codebase. 

Thanks!

**Comment by andrebrait** [comment]
Did it leave a stack trace? i.e. did it tell in which line of which file it happened?

**Comment by jonable** [comment]
Whoop, forgot include that part. 

```
In [30]: result = client.item(drive="me", path="\DemoFolder").children.request(top=3).get()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-ea896d866cfe> in <module>()
----> 1 result = client.item(drive="me", path="\DemoFolder").children.request(top=3).get()

~/.virtualenvs/onedrive/lib/python3.6/site-packages/msgraph/extensions/graph_client_helper.py in item(self, drive, id_, path)
     47
     48     if path:
---> 49         return drive_builder.item_by_path(path)
     50     elif id_:
     51         return drive_builder.items[id_]

AttributeError: 'DriveRequestBuilder' object has no attribute 'item_by_path'
```

Not sure if it helps this issue or should be in it's own thread, but I have to use the parameter "id_" instead of the documented "id" when calling GraphServiceClient.item().
```
In [30]: result = client.item(drive="me", id="{}".format('root'))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-f519bdea614c> in <module>()
----> 1 result = client.item(drive="me", id="{}".format('root'))

TypeError: item() got an unexpected keyword argument 'id'
```

**Comment by andrebrait** [comment]
> Not sure if it helps this issue or should be in it's own thread, but I have to use the parameter "id_" instead of the documented "id" when calling GraphServiceClient.item().

The parameter is id_. I don't know why, but it's correct.

I'll take a look at the issue if I have the time to do it.

The DriveRequestBuilder type really doesn't have a method called item_by_path in neither Python 2 or Python 3, and I really have no idea how it should be implemented. Someone at Microsoft will probably respond in this issue soon.

**Comment by caitlinrussell** [comment]
The models have not been updated in a while and are currently out of date with Graph's current API surface.
We are in the process of updating the SDK experience for this library. I will take the ID issue into consideration to ensure it is not duplicated in the next version.
In the meantime, I suggest using REST to get around this limitation.

**Comment by andrebrait** [comment]
@cbales Hey there. Regarding this update, do you guys have any idea when it would be complete? I'm asking because I'm thinking about sorta writing my own classes to interface with portions of the Graph API but I'll only start coding the app again in Q2 2018.

**Comment by caitlinrussell** [comment]
I don't have any exact dates, unfortunately. This is something we are actively working on however.

**Comment by caitlinrussell** [comment]
Closing as we are archiving this project
