### ISSUE TITLE
module microsoft is not found

### ISSUE THREAD

**Issue by dmikov** [microsoftarchive/msgraph-sdk-python#3]
Trying to run example and getting this error. Tried to run pip install microsoft, it cannot find it on pypi.
Something is missing from example instruction.
Also just to be clear, is there anyway to run it server side, without user interaction? I cannot seem to find good example on this custom Authorization provider. BTW why does it has to be custom? Why the authorization is not defined with a simple client_id, client_password, user, user_password provider?

**Comment by dmikov** [comment]
Regarding microsoft module, I can see it on web site, but pip search cannot find it, same as pip install

**Comment by shiftylogic** [comment]
First question, the library is actually 'msgraph' not 'microsoft'. The main README was patched. I'll dig around and see where the examples are incorrect.

Second question, the authentication service for accessing the Microsoft Graph is an OAuth2 implementation and therefore does not support supplying a straight user and password. Though there are ways to use client certificate authentication via our v1.0 authentication services, they require extra work, configuration, and care with respect to security. It is recommended that you use the standard user authentication flow for acquiring access and refresh tokens then manage the refresh tokens yourself. What components you use to accomplish the OAuth flow is up to you. The authentication provider you implement and supply to the graph client can perform this in whatever way makes sense for your application and then just supply a valid access token on-demand as you make graph calls.
