### ISSUE TITLE
class ToRecipientsCollectionPage does not exist

### ISSUE THREAD

**Issue by avandriets** [microsoftarchive/msgraph-sdk-python#4]

**Comment by shiftylogic** [comment]
Thanks for reporting this. We are working on a fix for this issue.

**Comment by nka11** [comment]
Is that related to a problem similar to #21 ?
Such errors makes this sdk quite useless for advanced use (unfortunately, it's the main purpose of it)

**Comment by caitlinrussell** [comment]
Closing as we are archiving this project
