### ISSUE TITLE
'module' object has no attribute 'get_default_client'

### ISSUE THREAD

**Issue by AlfredoCubitos** [microsoftarchive/msgraph-sdk-python#7]
after fixing the import problem I got this error running the example CommandLineFileExplorer.py
`'module' object has no attribute 'get_default_client'`
how to change this?
btw. in this example you have to change 
`import microsoft` to `import msgraph` I guess

**Comment by caitlinrussell** [comment]
Thanks for reporting this! We'll investigate this issue

**Comment by caitlinrussell** [comment]
Deprecated sample. Tracking new one here: #20
